completed week  4 assessment
learn-academy-2022-hotel/week-4-assessment-lmhazel pull request #1
Opened 2023-01-09 19:11 UTC by lmhazel

# Submitting Week 4 Assessment

### ✅ Completed Files

Mark the following as confirmation that the files in this repository are complete.

- [x ] JavaScript Coding Challenges
- [ x] Ruby Coding Challenges
- [ x] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2023-01-09 20:02 UTC, SunkissedQueen requested changes
Lea, change request to provide the definitions for the looking ahead terms.

2023-01-11 19:25 UTC, nmaresrivera11 commented on code-challenges.test.js
> +//Function: A fxn called shuffledArray which uses the .shift method to first remove the first variable in the array. Next using the .sort method and a random number generator using Math.random, the r
😍

2023-01-11 19:26 UTC, nmaresrivera11 commented on code-challenges.test.js
> +// const shuffledArray = (array) => {
Nice approach!

2023-01-11 19:28 UTC, nmaresrivera11 commented on code-challenges.test.js
> +//     expect(greeter()).toEqual(11)
greeter?

2023-01-11 19:30 UTC, nmaresrivera11 commented on ruby-challenges.rb
> +def number_checker num
Nice!

2023-01-11 19:30 UTC, nmaresrivera11 commented on ruby-challenges.rb
> +def vowel_remover string
Crushed it.

2023-01-11 19:50 UTC, nmaresrivera11 approved these changes
Lea, you did a really good job taking the tips from other assessments and implementing them in this one. Your pseudocode has more details and great vocabulary terms incorporated, your code has really good logic, and you're doing really well elaborating on talking points in your interview questions. This assessment comprehension level is advanced beginner. You can easily level this up with The Dreyfus model describing competent level as detailed pseudo code with proper vocabulary terms, "your answers" written in complete sentences the student's own words that provide correct answers, and well researched and detailed answers written in complete sentences in the student's own words that provides additional context. Great work!

2023-01-12 22:39 UTC, merged